AuthorName: Georg Graf
AuthorEmail: georg.ernst.graf@gmail.com
SourceCode: https://github.com/georgernstgraf/zazentimer
IssueTracker: https://github.com/georgernstgraf/zazentimer/issues
License: MIT
Categories:
  - Health & Fitness
  - Lifestyle
  - Time

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '3.0.7'
CurrentVersionCode: 3000700

Builds:
  - versionName: '3.0.7'
    versionCode: 3000700
    commit: v3.0.7
    gradle:
      - assemble
    gradleprops:
      - versionCode=3000700
      - versionName=3.0.7
    prebuild:
      - sed -i '/com.google.android.play.privacy-policy-url/d' app/src/main/AndroidManifest.xml
