AuthorName: Georg Graf
AuthorEmail: georg.ernst.graf@gmail.com
SourceCode: https://github.com/georgernstgraf/zazentimer
IssueTracker: https://github.com/georgernstgraf/zazentimer/issues
License: MIT
Categories:
  - Health & Fitness
  - Lifestyle
  - Time

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 3.2.0
CurrentVersionCode: 3020000

Builds:
  - versionName: 3.2.0
    versionCode: 3020000
    commit: v3.2.0
    gradle:
      - assemble
    gradleprops:
      - versionCode=3020000
      - versionName=3.2.0
    prebuild:
      - sed -i '/com.google.android.play.privacy-policy-url/d' app/src/main/AndroidManifest.xml
